# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Tournament.seed('名人', 'Meijin Title Match')
Tournament.seed('順位', 'Ranking League')
Tournament.seed('竜王', 'Ryuou Tournament')
Tournament.seed('王将', 'Oushou Championship')
Tournament.seed('王位', 'Oui Championship')
Tournament.seed('王座', 'Ouza Championship')
Tournament.seed('棋聖', 'Kisei Championship')
Tournament.seed('棋王', 'Kiou Championship')
Tournament.seed('朝日杯', 'Asahi Cup')
Tournament.seed('日本シリーズ', 'Japan Series')
Tournament.seed('女流名人', "Women's Meijin")
Tournament.seed('女流王座', "Women's Ouza")
Tournament.seed('マイナビ', "Mynavi Open")
Tournament.seed('女流王位', "Women's Oui")
Tournament.seed('倉敷藤花', "Kurashiki Wisteria")
Tournament.seed('鹿島杯', "Kashima Cup")

Player.seeds([
{name: 'Habu, Yoshiharu', search_key: '羽生善治', category: 1, kishi_id: 175, rank: 9, url: 'habu'},
{name: 'Itodani, Tetsuro', search_key: '糸谷哲郎', category: 1, kishi_id: 260, rank: 8, url: 'itodani'},
{name: 'Watanabe, Akira', search_key: '渡辺明', category: 1, kishi_id: 235, rank: 9, url: 'watanabe-a'},
{name: 'Tanigawa, Koji', search_key: '谷川浩司', category: 1, kishi_id: 131, rank: 9, url: 'tanigawa'},
{name: 'Sato, Yasumitsu', search_key: '佐藤康光', category: 1, kishi_id: 182, rank: 9, url: 'satou-y'},
{name: 'Moriuchi, Toshiyuki', search_key: '森内俊之', category: 1, kishi_id: 183, rank: 9, url: 'moriuti'},
{name: 'Kato, Hifumi', search_key: '加藤一二三'},
{name: 'Naito, Kunio', search_key: '内藤國雄'},
{name: 'Kiriyama, Kiyosumi', search_key: '桐山清澄'},
{name: 'Mori, Keiji', search_key: '森けい二'},
{name: 'Minami, Yoshikazu', search_key: '南芳一'},
{name: 'Takahashi, Michio', search_key: '高橋道雄'},
{name: 'Aono, Teruichi', search_key: '青野照市'},
{name: 'Tanaka, Torahiko', search_key: '田中寅彦'},
{name: 'Awaji, Hitoshige', search_key: '淡路仁茂'},
{name: 'Tanaka, Kaishu', search_key: '田中魁秀'},
{name: 'Fujii, Takeshi', search_key: '藤井猛'},
{name: 'Tsukada, Yasuaki', search_key: '塚田泰明'},
{name: 'Maruyama, Tadahisa', search_key: '丸山忠久'},
{name: 'Kobayashi, Kenji', search_key: '小林健二'},
{name: 'Goda, Masataka', search_key: '郷田真隆'},
{name: 'Morishita, Taku', search_key: '森下卓'},
{name: 'Yashiki, Nobuyuki', search_key: '屋敷伸之'},
{name: 'Fukuzaki, Bungo', search_key: '福崎文吾'},
{name: 'Nakamura, Osamu', search_key: '中村修'},
{name: 'Shima, Akira', search_key: '島朗'},
{name: 'Fukaura, Koichi', search_key: '深浦康市'},
{name: 'Kubo, Toshiaki', search_key: '久保利明'},
{name: 'Inoue, Keita', search_key: '井上慶太'},
{name: 'Tamaru, Noboru', search_key: '田丸昇'},
{name: 'Miura, Hiroyuki', search_key: '三浦弘行'},
{name: 'Senzaki, Manabu', search_key: '先崎学'},
{name: 'Waki, Kenji', search_key: '脇謙二'},
{name: 'Tomioka, Eisaku', search_key: '富岡英作'},
{name: 'Suzuki, Daisuke', search_key: '鈴木大介'},
{name: 'Abe, Takashi', search_key: '阿部隆'},
{name: 'Nakata, Hiroki', search_key: '中田宏樹'},
{name: 'Namekata, Hisashi', search_key: '行方尚史'},
{name: 'Kimura, Kazuki', search_key: '木村一基'},
{name: 'Nakagawa, Daisuke', search_key: '中川大輔'},
{name: 'Hiura, Ichiro', search_key: '日浦市郎'},
{name: 'Hashimoto, Takanori', search_key: '橋本崇載'},
{name: 'Urano, Masahiko', search_key: '浦野真彦'},
{name: 'Kitahama, Kensuke', search_key: '北浜健介'},
{name: 'Izumi, Masaki', search_key: '泉正樹'},
{name: 'Yamasaki, Takayuki', search_key: '山崎隆之'},
{name: 'Akutsu, Chikara', search_key: '阿久津主税'},
{name: 'Hirose, Akihito', search_key: '広瀬章人'},
{name: 'Kamiya, Hiroshi', search_key: '神谷広志'},
{name: 'Tosa, Koji', search_key: '土佐浩司'},
{name: 'Sato, Amahiko', search_key: '佐藤天彦'},
{name: 'Azuma, Kazuo', search_key: '東和男'},
{name: 'Miyata, Toshio', search_key: '宮田利男'},
{name: 'Nishikawa, Keiji', search_key: '西川慶二'},
{name: 'Oshima, Eiji', search_key: '大島映二'},
{name: 'Arimori, Kouzou', search_key: '有森浩三'},
{name: 'Kanzaki, Kenji', search_key: '神崎健二'},
{name: 'Murooka, Katsuhiko', search_key: '室岡克彦'},
{name: 'Horiguchi, Koji', search_key: '堀口弘治'},
{name: 'Hatakeyama, Naruyuki', search_key: '畠山成幸'},
{name: 'Horiguchi, Kazushiza', search_key: '堀口一史座'},
{name: 'Sanada, Keiichi', search_key: '真田圭一'},
{name: 'Nozuki, Hirotaka', search_key: '野月浩貴'},
{name: 'Shoshi, Kazuharu', search_key: '所司和晴'},
{name: 'Nakata, Isao', search_key: '中田功'},
{name: 'Naganuma, Hiroshi', search_key: '長沼洋'},
{name: 'Ogura, Hisashi', search_key: '小倉久史'},
{name: 'Hatakeyama, Mamoru', search_key: '畠山鎮'},
{name: 'Sugimoto, Masataka', search_key: '杉本昌隆'},
{name: 'Mori, Nobuo', search_key: '森信雄'},
{name: 'Chuza, Makoto', search_key: '中座真'},
{name: 'Matsuo, Ayumu', search_key: '松尾歩'},
{name: 'Ishikawa, Akio', search_key: '石川陽生'},
{name: 'Sato, Shuji', search_key: '佐藤秀司'},
{name: 'Toyokawa, Takahiro', search_key: '豊川孝弘'},
{name: 'Iizuka, Hiroki', search_key: '飯塚祐紀'},
{name: 'Kobayashi, Hiroshi (167)', search_key: '小林宏'},
{name: 'Iijima, Eiji', search_key: '飯島栄治'},
{name: 'Kobayashi, Hiroshi (223)', search_key: '小林裕士'},
{name: 'Hirafuji, Shingo', search_key: '平藤真吾'},
{name: 'Toyoshima, Masayuki', search_key: '豊島将之'},
{name: 'Tamura, Kosuke', search_key: '田村康介'},
{name: 'Fujiwara, Naoya', search_key: '藤原直哉'},
{name: 'Inaba, Akira', search_key: '稲葉陽'},
{name: 'Murayama, Yasuaki', search_key: '村山慈明'},
{name: 'Kitajima, Tadao', search_key: '北島忠雄'},
{name: 'Anzai, Shoichi', search_key: '安西勝一'},
{name: 'Kinoshita, Koichi', search_key: '木下浩一'},
{name: 'Ito, Hirofumi', search_key: '伊藤博文'},
{name: 'Takada, Shohei', search_key: '高田尚平'},
{name: 'Okazaki, Hiroshi', search_key: '岡崎洋'},
{name: 'Kawakami, Takeshi', search_key: '川上猛'},
{name: 'Yagura, Norihiro', search_key: '矢倉規広'},
{name: 'Kubota, Yoshiyuki', search_key: '窪田義行'},
{name: 'Katsumata, Kiyokazu', search_key: '勝又清和'},
{name: 'Kondo, Masakazu', search_key: '近藤正和'},
{name: 'Sato, Shinnya', search_key: '佐藤紳哉'},
{name: 'Ina, Yusuke', search_key: '伊奈祐介'},
{name: 'Matsumoto, Yoshiyuki', search_key: '松本佳介'},
{name: 'Murata, Tomohiro', search_key: '村田智弘'},
{name: 'Annyouji, Takanori', search_key: '安用寺孝功'},
{name: 'Katagami, Daisuke', search_key: '片上大輔'},
{name: 'Masuda, Yuji', search_key: '増田裕司'},
{name: 'Muranaka, Shuji', search_key: '村中秀史'},
{name: 'Tobe, Makoto', search_key: '戸辺誠'},
{name: 'Miyata, Atsushi', search_key: '宮田敦史'},
{name: 'Chiba, Sakio', search_key: '千葉幸生'},
{name: 'Takano, Hideyuki', search_key: '高野秀行'},
{name: 'Nishio, Akira', search_key: '西尾明'},
{name: 'Sasaki, Makoto', search_key: '佐々木慎'},
{name: 'Ito, No', search_key: '伊藤能'},
{name: 'Nakamura, Taichi', search_key: '中村太地'},
{name: 'Takasaki, Issei', search_key: '高崎一生'},
{name: 'Yokoyama, Hiroaki', search_key: '横山泰明'},
{name: 'Oishi, Tadashi', search_key: '大石直嗣'},
{name: 'Nagase, Takuya', search_key: '永瀬拓矢'},
{name: 'Sato, Kazutoshi', search_key: '佐藤和俊'},
{name: 'Oikawa, Takuma', search_key: '及川拓馬'},
{name: 'Sawada, Shingo', search_key: '澤田真吾'},
{name: 'Yamamoto, Shinnya', search_key: '山本真也'},
{name: 'Ohira, Takehiro', search_key: '大平武洋'},
{name: 'Kanezawa, Takashi', search_key: '金沢孝史'},
{name: 'Ueno, Hirokazu', search_key: '上野裕和'},
{name: 'Nakao, Toshiyuki', search_key: '中尾敏之'},
{name: 'Nakamura, Ryosuke', search_key: '中村亮介'},
{name: 'Sakaguchi, Satoru', search_key: '阪口悟'},
{name: 'Kanai, Kota', search_key: '金井恒太'},
{name: 'Nagaoka, Yuya', search_key: '長岡裕也'},
{name: 'Toyama, Yusuke', search_key: '遠山雄亮'},
{name: 'Kumasaka, Manabu', search_key: '熊坂学'},
{name: 'Shimamoto, Ryo', search_key: '島本亮'},
{name: 'Sugai, Tatsuya', search_key: '菅井竜也'},
{name: 'Abe, Kenjiro', search_key: '阿部健治郎'},
{name: 'Murata, Akihiro', search_key: '村田顕弘'},
{name: 'Funae, Kohei', search_key: '船江恒平'},
{name: 'Fujikura, Yuki', search_key: '藤倉勇樹'},
{name: 'Segawa, Shoji', search_key: '瀬川晶司'},
{name: 'Yoshida, Masakazu', search_key: '吉田正和'},
{name: 'Saito, Shintaro', search_key: '斎藤慎太郎'},
{name: 'Ito, Shingo', search_key: '伊藤真吾'},
{name: 'Sasaki, Yuki', search_key: '佐々木勇気'},
{name: 'Takami, Taichi', search_key: '高見泰地'},
{name: 'Nishikawa, Kazuhiro', search_key: '西川和宏'},
{name: 'Tanaka, Yuichi', search_key: '田中悠一'},
{name: 'Abe, Koru', search_key: '阿部光瑠'},
{name: 'Sato, Shinnichi', search_key: '佐藤慎一'},
{name: 'Chida, Shota', search_key: '千田翔太'},
{name: 'Makino, Mitsunori', search_key: '牧野光則'},
{name: 'Kadokura, Keita', search_key: '門倉啓太'},
{name: 'Fujimori, Tetsuya', search_key: '藤森哲也'},
{name: 'Yashiro, Wataru', search_key: '八代弥'},
{name: 'Kamimura, Wataru', search_key: '上村亘'},
{name: 'Ishida, Naohiro', search_key: '石田直裕'},
{name: 'Watanabe, Hiromu', search_key: '渡辺大夢'},
{name: 'Takeuchi, Yugo', search_key: '竹内雄悟'},
{name: 'Ishii, Kentaro', search_key: '石井健太郎'},
{name: 'Sanmaido, Tatsuya', search_key: '三枚堂達也'},
{name: 'Hoshino, Yoshitaka', search_key: '星野良生'},
{name: 'Miyamoto, Hiroshi', search_key: '宮本広志'},
{name: 'Masuda, Yasuhiro', search_key: '増田康宏'},
{name: 'Kurosawa, Leo', search_key: '黒沢怜生'},
{search_key: '千葉涼子', name: 'Chiba, Ryoko'},
{search_key: '里見香奈', name: 'Satomi, Kana'},
{search_key: '清水市代', name: 'Shimizu, Ichiyo'},
{search_key: '鈴木環那', name: 'Suzuki, Kanna'},
{search_key: '室谷由紀', name: 'Muroya, Yuki'},
{search_key: '中井広恵', name: 'Nakai, Hiroe'},
{search_key: '矢内理絵子', name: 'Yauchi, Rieko'},
{search_key: '貞升南', name: 'Sadamasu, Minami'},
{search_key: '中倉宏美', name: 'Nakakura, Hiromi'},
{search_key: '本田小百合', name: 'Honda, Sayuri'},
{search_key: '室田伊緒', name: 'Murota, Io'},
{search_key: '岩根忍', name: 'Iwane, Shinobu'},
{search_key: '上田初美', name: 'Ueda, Hatsumi'},
{search_key: '和田あき', name: 'Wada, Aki'},
{search_key: '真田彩子', name: 'Sanada, Ayako'},
{search_key: '村田智穂', name: 'Murata, Chiho'},
{search_key: '相川春香', name: 'Aikawa, Haruka'},
{search_key: '蛸島彰子', name: 'Takojima, Akiko'},
{search_key: '野田澤彩乃', name: 'Nodasawa, Ayano'},
{search_key: '藤田綾', name: 'Fujita, Aya'},
{search_key: '北尾まどか', name: 'Kitao, Madoka'},
{search_key: '安食総子', name: 'Ajiki, Fusako'},
{search_key: '山田朱未', name: 'Yamada, Akemi'},
{search_key: '植村真理', name: 'Uemura, Mari'},
{search_key: '石高澄恵', name: 'Ishitaka, Sumie'},
{search_key: '大庭美樹', name: 'Oba, Miki'},
{search_key: '井道千尋', name: 'Ido, Chihiro'},
{search_key: '渡辺弥生', name: 'Watanabe, Mio'},
{search_key: '山口恵梨子', name: 'Yamaguchi, Eriko'},
{search_key: '香川愛生', name: 'Kagawa, Manao'},
{search_key: '中村真梨花', name: 'Nakamura, Marika'},
{search_key: '中村桃子', name: 'Nakamura, Momoko'},
{search_key: '伊奈川愛菓', name: 'Inagawa, Manaka'},
{search_key: '熊倉紫野', name: 'Kumakura, Shino'},
{search_key: '中倉彰子', name: 'Nakakura, Akiko'},
{search_key: '長沢千和子', name: 'Nagasawa, Chikako'},
{search_key: '上川香織', name: 'Uekawa, Kaori'},
{search_key: '久津知子', name: 'Hisatsu, Tomoko'},
{search_key: '竹部さゆり', name: 'Takebe, Sayuri'},
{search_key: '島井咲緒里', name: 'Shimai, Saori'},
{search_key: '甲斐智美', name: 'Kai, Tomomi'},
{search_key: '早水千紗', name: 'Hayamizu, Chisa'},
{search_key: '石橋幸緒', name: 'Ishibashi, Sachio'},
{search_key: '長谷川優貴', name: 'Hasegawa, Yuki'},
{search_key: '高群佐知子', name: 'Takamure, Sachiko'},
{search_key: '山田久美', name: 'Yamada, Kumi'},
{search_key: '斎田晴子', name: 'Saida, Haruko'},
{search_key: '渡部愛', name: 'Watanabe, Mana'},
{search_key: '竹俣紅', name: 'Takemata, Beni'},
{search_key: '北村桂香', name: 'Kitamura, Keika'},
{search_key: '飯野愛', name: 'Iino, Ai'},
{search_key: '塚田恵梨花', name: 'Tsukada, Erika'},
{search_key: '加藤桃子', name: 'Kato, Momoko'},
{search_key: '鹿野圭生', name: 'Kano, Tamao'},
{search_key: '船戸陽子', name: 'Funato, Yoko'},
{search_key: '山根ことみ', name: 'Yamane, Kotomi'},
{search_key: '伊藤沙恵', name: 'Ito, Sae'},
{search_key: '高浜愛子', name: 'Takahama, Aiko'},
{search_key: '山口絵美菜', name: 'Yamaguchi, Emina'}
])

